Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -68,6 +68,14 @@ jobs:
       - name: Install Hatch
         run: uv tool install hatch
 
+      - name: Check for Missing Feature File
+        run: |
+          FEATURE_PATH="tests/v3/compatibility_suite/definition/features/V1/http_consumer.feature"
+          if [ ! -f "$FEATURE_PATH" ]; then
+            echo "Error: Feature file '$FEATURE_PATH' is missing!"
+            exit 1
+          fi
+
       - name: Run tests
         run: hatch run test --broker-url=${{ env.PACT_BROKER_URL }} --container
 
